name: SCALEWAY

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven repository
      uses: actions/cache@v1
      with:
        path: .m2/repository # maven repository files are stored here
        key: ${{ runner.OS }}-maven-${{ hashFiles('pom.xml') }}
        restore-keys: |
            ${{ runner.OS }}-maven-
            ${{ runner.OS }}-
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - uses: actions/upload-artifact@v1
        # Test run screenshots only on failure
      if: success()
      with:
        name: preview-services-runner.jar
        path: target/preview-services-runner.jar
